# -*- coding: utf-8 -*-
"""Task_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LDN17PiUFZI2-VpOkcAYPfNkrrAvUXgz
"""

def compute(n):
    if n < 10:
        out = n ** 2
    elif n <= 20:  # Changed from n < 20 to n <= 20
        out = 1
        for i in range(1, n-10 + 1):  # Changed the range end value
            out *= i
    else:
        lim = n - 20
        out = (lim * (lim + 1)) // 2  # Corrected the formula
    print(out)

n = int(input("Enter an integer: "))
compute(n)