# -*- coding: utf-8 -*-
"""Task_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1atMZFM_ugxuKQBZs7kSSr89r4rxEFxBL
"""

import csv

def generate_report(csv_files):
  """Generates a report from multiple CSV files.

  Args:
    csv_files: A list of CSV file paths.

  Returns:
    A string containing the report data.
  """

  report_data = ""

  for csv_file in csv_files:
    with open(csv_file, "r") as f:
      reader = csv.reader(f)

      # Read the header row.
      header_row = next(reader)

      # Iterate over the data rows.
      for data_row in reader:
        report_data += ",".join(data_row) + "\n"

  return report_data

def main():
  """Generates a report from multiple CSV files."""

  # Get the list of CSV files.
  csv_files = ["Department.csv", "Employee.csv","Salaries.csv"]

  # Generate the report.
  report_data = generate_report(csv_files)

  # Save the report to a file.
  with open("report.txt", "w") as f:
    f.write(report_data)

if __name__ == "__main__":
  main()